@baseURL = https://localhost:8443

# Create new user
POST {{baseURL}}/users
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/87.0.4280.101 Safari/537.36
content-type: application/json

{
  "email": "CooL2@tEst.com",
  "password": "neW9$tes51t9"
}

###
# @name login
POST {{baseURL}}/sessions
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/87.0.4280.101 Safari/537.36
content-type: application/json

{
  "email": "cooL3@tEst.com",
  "password": "neW9$tes51t9"
}

###

@userID = {{login.response.body._id}}
@sessionID = {{login.response.body.session._id}}
@authToken = {{login.response.headers.x-access-token}}

# Get user profile
GET {{baseURL}}/users/{{userID}}
x-access-token: {{authToken}}
content-type: application/json

###
# Get all users as admin
GET {{baseURL}}/users
  ?roles=admin
  &page=0
  &max_page=3
x-access-token: {{authToken}}
content-type: application/json 

###
# Update profile
PUT {{baseURL}}/users/{{userID}}
x-access-token: {{authToken}}
content-type: application/json

{
  "email": "cooL3@tEst.com",
  "password": "neW9$tes51t9"
}

###
# Log out user
DELETE {{baseURL}}/sessions/{{sessionID}}
x-access-token: {{authToken}}
content-type: application/json

###
# Delete user
DELETE {{baseURL}}/users/{{userID}}
x-access-token: {{authToken}}
content-type: application/json