@baseURL = https://localhost:8443

# Create new user
POST {{baseURL}}/users
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/87.0.4280.101 Safari/537.36
content-type: application/json

{
  "email": "cool3@tEst.com",
  "password": "neW9$tes51t9"
}

###
# @name login
POST {{baseURL}}/sessions
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/87.0.4280.101 Safari/537.36
content-type: application/json

{
  "email": "cool3@tEst.com",
  "password": "neW9$tes51t9"
}

###

@userID = {{login.response.body._id}}
@sessionID = {{login.response.body.sessions[0]._id}}
@authToken = {{login.response.headers.x-access-token}}

# Get user profile
GET {{baseURL}}/users/{{userID}}
x-access-token: {{authToken}}
content-type: application/json

###
# Create a new note
# @name note
POST {{baseURL}}/notes
x-access-token: {{authToken}}
content-type: application/json

{
  "title": "Does it work test",
  "body": "This is the body text",
  "tags": ["tag5", "tag9"],
  "favorite": true
}
###
@noteID = {{note.response.body.note._id}}

###
# Get a note
GET {{baseURL}}/notes/{{noteID}}
x-access-token: {{authToken}}
content-type: application/json 

###
# Update a note
PUT {{baseURL}}/notes/{{noteID}}
x-access-token: {{authToken}}
content-type: application/json 

{
  "title": "Updated",
  "body": "This is the body text that has been updated",
  "tags": ["tag15", "tag19"],
  "favorite": false
}
###
# Delete a note
DELETE {{baseURL}}/notes/{{noteID}}
x-access-token: {{authToken}}
content-type: application/json 

###
# Get all notes
GET {{baseURL}}/notes
  ?favorite=true
x-access-token: {{authToken}}
content-type: application/json 

###
# Upload a new file
# @name upload
POST {{baseURL}}/files/{{noteID}}
x-access-token: {{authToken}}
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="track"; filename="test.png"
Content-Type: application/octet-stream

< ./test.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
@uploadID = {{upload.response.body.file_id}}

###
# Get file
GET {{baseURL}}/files/{{uploadID}}
x-access-token: {{authToken}}

###
# Delete file
DELETE {{baseURL}}/files/{{uploadID}}
x-access-token: {{authToken}}

###
# Get all users as admin
GET {{baseURL}}/users
  ?roles=admin
  &page=0
  &max_page=3
x-access-token: {{authToken}}
content-type: application/json 

###
# Update profile
PUT {{baseURL}}/users/{{userID}}
x-access-token: {{authToken}}
content-type: application/json

{
  "email": "cooL5@tEst.com",
  "password": "neW9$tes51t9"
}

###
# Log out user
DELETE {{baseURL}}/sessions/{{sessionID}}
x-access-token: {{authToken}}
content-type: application/json

###
# Delete user
DELETE {{baseURL}}/users/{{userID}}
x-access-token: {{authToken}}
content-type: application/json