version: "3"
services:
    db:
      image: mongo
      ports:
      - "27017:27017"
      restart: always
      env_file:
      - .env.docker
      volumes:
      - ./api/models/:/docker-entrypoint-initdb.d
    swagger:
      image: swaggerapi/swagger-ui
      ports:
      - "8080:8080"
      volumes: 
      - ./api/:/notes
      environment:
          SWAGGER_JSON: /notes/swagger.yaml
    api:
        build: api/
        ports:
        - "8081:8081"
        - "8443:8443"
        working_dir: /app/notes
        volumes: 
        - ./api/:/app/notes
        environment:
            PATH: /app/node_modules/.bin:$PATH
        depends_on:
        - db